name: "Build and Release Swiftfin"

on:
  workflow_dispatch:
    inputs:
      bundle_id:
        description: "Modify the bundle ID (optional)"
        default: "com.yourcompany.swiftfin"
        required: false
        type: string
      app_name:
        description: "Modify the name of the app on the Home Screen (optional)"
        default: "Swiftfin"
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Swiftfin
    runs-on: macos-14
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: brew install ldid dpkg make

      - name: Install SwiftGen
        run: brew install swiftgen

      - name: Set Xcode Version
        run: sudo xcode-select -s "/Applications/Xcode_15.3.app"

      - name: Cache Carthage
        uses: actions/cache@v4
        id: carthage-cache
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: ${{ runner.os }}-carthage-

      - name: Update Carthage
        run: carthage update --use-xcframeworks --cache-builds

      - name: Build the Project
        run: |
          xcodebuild clean build \
          -project "Swiftfin.xcodeproj" \
          -scheme "Swiftfin" \
          -configuration Release \
          -derivedDataPath build/derived_data \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Verify Build Output
        run: |
          echo "Contents of build/derived_data/Build/Products/Release-iphoneos:"
          ls build/derived_data/Build/Products/Release-iphoneos/

      - name: Create Payload Directory
        run: mkdir -p build/Payload

      - name: Copy App to Payload
        run: cp -r build/derived_data/Build/Products/Release-iphoneos/"Swiftfin iOS.app" build/Payload

      - name: Fake Code Sign the App
        run: ldid -S build/Payload/"Swiftfin iOS.app"/Swiftfin

      - name: Package IPA
        run: |
          cd build
          zip -r Swiftfin.ipa Payload

      - name: Upload IPA as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Swiftfin-ipa
          path: build/Swiftfin.ipa
